### ISSUE TITLE
TimeoutError when calling default scripts

### ISSUE THREAD

**Issue by comraderoyce** [kengz/aiva#10]
Getting TimeoutErros when calling most of the AI scripts. 

Basic hubot scripts and simple message replies (i.e. messaging "titanic") work, but not the more complicated ones. 

Running from the docker image using Slack adapter. 

`Unhandled rejection TimeoutError: operation timed out
  at tryOnTimeout (timers.js:224:11)
  at Timer.listOnTimeout (timers.js:198:5)
From previous event:
  at cdefer (/opt/aiva/lib/client.js:167:6)
  at pass (/opt/aiva/lib/client.js:111:15)
  at TextListener.callback (/opt/aiva/scripts/translate.js:28:12)
  at /opt/aiva/node_modules/hubot/src/listener.coffee:65:12
  at allDone (/opt/aiva/node_modules/hubot/src/middleware.coffee:44:37)
  at /opt/aiva/node_modules/hubot/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/opt/aiva/node_modules/hubot/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/opt/aiva/node_modules/hubot/node_modules/async/lib/async.js:268:15)
  at /opt/aiva/node_modules/hubot/src/middleware.coffee:49:13
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by kengz** [comment]
Hi,

It seems that the JS client can't reach the Python client. Normally they talk through socket.io.

Did you start the bot using the `npm start` command? It should automatically start the py and rb clients in `lib/`

**Comment by comraderoyce** [comment]
I did start the bot with `npm start` and then ran supervisord once in the docker instance. 

That starts the bot up fine and I'm able to use Slack to ping the bot and run any of the commands that don't require routing between clients. 

It looks like there are some build errors with node-gyp when starting up. 

Is there any way to check if socket.io is running once in the docker container?

**Comment by kengz** [comment]
yes, if you uncomment [this snippet](https://github.com/kengz/aiva/blob/master/lib/client.js#L181) and run the script while the bot is started. 

Also the system will make sure that all clients have joined, and [logs the confirmation if so](https://github.com/kengz/aiva/blob/master/lib/io_start.js#L51). Do u see that message in your stdout?

**Comment by comraderoyce** [comment]
Yeah it seems like there is an issue with Socket.io starting up. I'm getting most of the correct log messages, but then never getting a "Clients have joined" message. The bot still connects to Slack and I can ping the bot, but here are the logs: 

`Royces-MacBook-Pro:aiva royce$ npm start

> aiva@3.2.1 start /Users/royce/aiva
> bin/start.sh

[ ----- Docker image kengz/aiva pulled, using it ------ ]
[ -------- Use Ctrl-p-q to detach bash session -------- ]\n
[ Development: Creating new Docker container 'aiva-development' ]
[ ---------------- To run: supervisord ---------------- ]\n
root@cc8fee1e536e:/opt/aiva# supervisord
/usr/lib/python2.7/dist-packages/supervisor/options.py:295: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2016-07-29 18:01:58,099 CRIT Set uid to user 0
2016-07-29 18:01:58,099 WARN Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2016-07-29 18:01:58,129 INFO RPC interface 'supervisor' initialized
2016-07-29 18:01:58,130 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2016-07-29 18:01:58,130 INFO supervisord started with pid 66
2016-07-29 18:01:59,133 INFO spawned: 'run_nginx' with pid 69
2016-07-29 18:01:59,136 INFO spawned: 'run_aiva' with pid 70

> aiva@3.2.1 gi /opt/aiva
> npm i; mkdir -p ./logs; npm run pip3; npm run bundler

2016-07-29 18:02:01,111 INFO success: run_nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-07-29 18:02:01,112 INFO success: run_aiva entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
^C2016-07-29 18:02:02,585 WARN received SIGINT indicating exit request
2016-07-29 18:02:02,586 INFO waiting for run_nginx, run_aiva to die
2016-07-29 18:02:03,588 INFO stopped: run_aiva (terminated by SIGTERM)
2016-07-29 18:02:03,615 INFO stopped: run_nginx (exit status 0)
root@cc8fee1e536e:/opt/aiva# ^C
root@cc8fee1e536e:/opt/aiva# npm start

> aiva@3.2.1 start /opt/aiva
> bin/start.sh

[ ------- Starting on local machine, not Docker ------- ]

> aiva@3.2.1 development /opt/aiva
> if [ $npm_config_bot ]; then bot=$npm_config_bot; else bot=aivadev; fi; NODE_ENV=development DEPLOY=.keys-$bot BOTNAME=$bot forever --minUptime=1000 --spinSleepTime=1000 --killSignal=SIGTERM --uid $bot -m 10 -a index.js | tee ./logs/$bot.log

[Fri Jul 29 2016 18:02:10 GMT+0000 (UTC)] INFO Using: .keys-aivadev in NODE_ENV: development
[Fri Jul 29 2016 18:02:10 GMT+0000 (UTC)] INFO http://localhost:4040-4041 used for ngrok
[Fri Jul 29 2016 18:02:10 GMT+0000 (UTC)] INFO http://localhost:7476 used for neo4j
[Fri Jul 29 2016 18:02:10 GMT+0000 (UTC)] INFO http://localhost:6466 used for socketIO
[Fri Jul 29 2016 18:02:10 GMT+0000 (UTC)] INFO http://localhost:8345 used for slack
[Fri Jul 29 2016 18:02:10 GMT+0000 (UTC)] INFO http://localhost:8443 used for telegram
[Fri Jul 29 2016 18:02:10 GMT+0000 (UTC)] INFO http://localhost:8545 used for fb
Using NEO4J_AUTH: 'neo4j:0000'
Starting Neo4j.
Started neo4j (pid 241). By default, it is available at http://localhost:7474/
There may be a short delay until the server is ready.
See /var/log/neo4j/neo4j.log for current status.
Attempting to verify/set your NEO4J_AUTH in the background ...
Changing default Neo4j password
NEO4J_AUTH valid, auth successful
[Fri Jul 29 2016 18:02:22 GMT+0000 (UTC)] INFO Starting socket.io server on IOPORT: 6466
[Fri Jul 29 2016 18:02:23 GMT+0000 (UTC)] INFO Starting polyglot io_clients
import js scripts from client.js
[Fri Jul 29 2016 18:02:25 GMT+0000 (UTC)] INFO Deploy bot: aivadev with adapter: slack
[Fri Jul 29 2016 18:02:26 GMT+0000 (UTC)] INFO js /#0gMq9x8vfB8e7p5oAAAA joined
[Fri Jul 29 2016 18:02:26 GMT+0000 (UTC)] ERROR err: /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:95:in `block in materialize'
[Fri Jul 29 2016 18:02:26 GMT+0000 (UTC)] ERROR err: : 
[Fri Jul 29 2016 18:02:26 GMT+0000 (UTC)] ERROR err: Bundler::GemNotFound
[Fri Jul 29 2016 18:02:26 GMT+0000 (UTC)] ERROR err: 

[Fri Jul 29 2016 18:02:26 GMT+0000 (UTC)] ERROR err: 	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `map!'

[Fri Jul 29 2016 18:02:26 GMT+0000 (UTC)] ERROR err: 	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `materialize'

[Fri Jul 29 2016 18:02:26 GMT+0000 (UTC)] ERROR err: 	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'

[Fri Jul 29 2016 18:02:26 GMT+0000 (UTC)] ERROR err: 	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:185:in `specs_for'

[Fri Jul 29 2016 18:02:26 GMT+0000 (UTC)] ERROR err: 	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:174:in `requested_specs'
	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/environment.rb:19:in `requested_specs'
	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:14:in `setup'
	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/setup.rb:19:in `<top (required)>'
	from /root/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /root/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /root/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /opt/aiva/lib/client.rb:4:in `<main>'

[Fri Jul 29 2016 18:02:31 GMT+0000 (UTC)] INFO Connecting...
[Fri Jul 29 2016 18:02:32 GMT+0000 (UTC)] INFO Logged in as aiva of Comrade, but not yet connected
[Fri Jul 29 2016 18:02:33 GMT+0000 (UTC)] INFO Slack client now connected
TimeoutError: operation timed out
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
From previous event:
    at cdefer (/opt/aiva/lib/client.js:167:6)
    at pass (/opt/aiva/lib/client.js:111:15)
    at Object.<anonymous> (/opt/aiva/lib/client.js:181:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at io_client (/opt/aiva/lib/io_start.js:109:3)
    at io_server (/opt/aiva/lib/io_start.js:85:3)
    at io_start (/opt/aiva/lib/io_start.js:136:3)
    at Object.<anonymous> (/opt/aiva/index.js:177:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
Model loaded from /opt/aiva/lib/py/ais/models/dnn_titanic
[Fri Jul 29 2016 18:02:49 GMT+0000 (UTC)] ERROR err: Traceback (most recent call last):
  File "/opt/aiva/lib/client.py", line 39, in <module>
    from py import *
  File "/opt/aiva/lib/py/nlp.py", line 8, in <module>
    nlp = English()
  File "/usr/local/lib/python3.4/dist-packages/spacy/language.py", line 190, in __init__
    parser = self.default_parser(package, self.vocab)
  File "/usr/local/lib/python3.4/dist-packages/spacy/language.py", line 123, in default_parser
    return Parser.from_dir(data_dir, vocab.strings, ArcEager)
  File "spacy/syntax/parser.pyx", line 98, in spacy.syntax.parser.Parser.from_dir (spacy/syntax/parser.cpp:5759)
  File "thinc/linear/avgtron.pyx", line 91, in thinc.linear.avgtron.AveragedPerceptron.load (thinc/linear/avgtron.cpp:3120)
  File "thinc/linear/serialize.pyx", line 100, in thinc.linear.serialize.Reader.read (thinc/linear/serialize.cpp:2397)
MemoryError

[Fri Jul 29 2016 18:02:52 GMT+0000 (UTC)] WARNING Anchors don't work well with respond, perhaps you want to use 'hear'
[Fri Jul 29 2016 18:02:52 GMT+0000 (UTC)] WARNING The regex in question was /^(\S+[^+:\s])[: ]*(\+\+|ftw!*)\s*($)/i
[Fri Jul 29 2016 18:02:52 GMT+0000 (UTC)] ERROR Last pong is too old: 19.394
[Fri Jul 29 2016 18:02:52 GMT+0000 (UTC)] INFO Reconnecting in 1000ms
[Fri Jul 29 2016 18:02:53 GMT+0000 (UTC)] INFO Slack client closed, waiting for reconnect
[Fri Jul 29 2016 18:02:53 GMT+0000 (UTC)] INFO js /#fTaZqDpPYxB0uqZjAAAB joined
[Fri Jul 29 2016 18:02:53 GMT+0000 (UTC)] INFO Attempting reconnect
[Fri Jul 29 2016 18:02:53 GMT+0000 (UTC)] INFO Connecting...
[Fri Jul 29 2016 18:02:54 GMT+0000 (UTC)] INFO Logged in as aiva of Comrade, but not yet connected
[Fri Jul 29 2016 18:02:55 GMT+0000 (UTC)] INFO Slack client now connected
[Fri Jul 29 2016 18:02:57 GMT+0000 (UTC)] INFO setting global.users from scripts/serialize_users.js
TimeoutError: operation timed out
  at tryOnTimeout (timers.js:224:11)
  at Timer.listOnTimeout (timers.js:198:5)
From previous event:
  at cdefer (/opt/aiva/lib/client.js:167:6)
  at pass (/opt/aiva/lib/client.js:111:15)
  at Object.<anonymous> (/opt/aiva/lib/client.js:181:1)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (/opt/aiva/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at /opt/aiva/scripts/_init.js:26:5
  at undefined.next (native)
  at onFulfilled (/opt/aiva/node_modules/co/index.js:65:19)
  at /opt/aiva/node_modules/co/index.js:54:5
From previous event:
  at co (/opt/aiva/node_modules/co/index.js:50:10)
  at module.exports (/opt/aiva/scripts/_init.js:24:3)
  at Robot.loadFile (/opt/aiva/node_modules/hubot/src/robot.coffee:358:11)
  at Robot.load (/opt/aiva/node_modules/hubot/src/robot.coffee:377:10)
  at SlackBot.loadScripts (/opt/aiva/node_modules/hubot/bin/hubot:97:13)
  at SlackBot.g (events.js:286:16)
  at emitNone (events.js:86:13)
  at SlackBot.emit (events.js:185:7)
  at SlackBot.open (/opt/aiva/node_modules/hubot-slack/src/slack.coffee:100:6)
  at Client.<anonymous> (/opt/aiva/node_modules/hubot-slack/src/slack.coffee:1:1)
  at emitNone (events.js:86:13)
  at Client.emit (events.js:185:7)
  at Client.onMessage (/opt/aiva/node_modules/slack-client/src/client.js:450:21)
  at WebSocket.<anonymous> (/opt/aiva/node_modules/slack-client/src/client.js:140:24)
  at emitTwo (events.js:106:13)
  at WebSocket.emit (events.js:191:7)
  at Receiver.self._receiver.ontext (/opt/aiva/node_modules/ws/lib/WebSocket.js:697:10)
  at Receiver.opcodes.1.finish (/opt/aiva/node_modules/ws/lib/Receiver.js:397:14)
  at Receiver.<anonymous> (/opt/aiva/node_modules/ws/lib/Receiver.js:384:31)
  at Receiver.add (/opt/aiva/node_modules/ws/lib/Receiver.js:93:24)
  at TLSSocket.firstHandler (/opt/aiva/node_modules/ws/lib/WebSocket.js:678:22)
  at emitOne (events.js:96:13)
  at TLSSocket.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:172:18)
  at TLSSocket.Readable.push (_stream_readable.js:130:10)
  at TLSWrap.onread (net.js:542:20)`

**Comment by kengz** [comment]
Heya sorry was away on vacation.
Found the problems:

`[Fri Jul 29 2016 18:02:26 GMT+0000 (UTC)] ERROR err: Bundler::GemNotFound`

and

```
[Fri Jul 29 2016 18:02:49 GMT+0000 (UTC)] ERROR err: Traceback (most recent call last):
  File "/opt/aiva/lib/client.py", line 39, in <module>
    from py import *
  File "/opt/aiva/lib/py/nlp.py", line 8, in <module>
    nlp = English()
```

So it seems your system is missing the Bundler for ruby, and a proper [Spacy](https://spacy.io/) installation. Either try to install them or mute the Ruby and Python clients (thus modules) altogether [here](https://github.com/kengz/aiva/blob/master/lib/io_start.js#L112)

**Comment by kengz** [comment]
Solved in v4 release with better Promise chaining and logging
