### ISSUE TITLE
npm setup error :(

### ISSUE THREAD

**Issue by kumarabd** [kengz/aiva#44]
Hey

Ive been trying to setup the environment in kali linux and keeps showing error. Can anyone help me out with this?
Ive pasted the error below:
``Nodejs is already installed
Python3 is already installed
MySQL is already installed
MySQL is already started
Neo4j is already installed
Pip modules already installed
spaCy model:
/usr/bin/python3: No module named sputnik
/usr/bin/python: No module named spacy.en
Npm modules already installed
/home/hulkbuster/Documents/aiva/src/db.js:2
const { exec } = require('child_process')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

Sequelize [Node: 4.8.4, CLI: 2.8.0, ORM: 3.30.4]

Loaded configuration file "config/db.json".
Using environment "development".
Unable to connect to database: SequelizeConnectionError: ER_BAD_DB_ERROR: Unknown database 'aiva_dev'

Sequelize [Node: 4.8.4, CLI: 2.8.0, ORM: 3.30.4]

Loaded configuration file "config/db.json".
Using environment "test".
Unable to connect to database: SequelizeConnectionError: ER_BAD_DB_ERROR: Unknown database 'aiva_test'

Sequelize [Node: 4.8.4, CLI: 2.8.0, ORM: 3.30.4]

Loaded configuration file "config/db.json".
Using environment "production".
Unable to connect to database: SequelizeConnectionError: ER_BAD_DB_ERROR: Unknown database 'aiva_prod'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aiva@4.2.0 setup: `bin/setup`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aiva@4.2.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-05T13_39_51_677Z-debug.log``

**Comment by kengz** [comment]
sequelize was likely not ran, hence the missing DBs. Solutions:
- the version of `node` needs to be at least `6`,
- and by any chance if your python is in a virtualenv, make sure these are installed:
```shell
python3 -m pip install -U six
python3 -m pip install -U autocorrect
python3 -m pip install -U websocket
python3 -m pip install -U socketIO-client
python3 -m pip install -U spacy
```
