### ISSUE TITLE
AIVA Components failed to load

### ISSUE THREAD

**Issue by akashpatelj93** [kengz/aiva#57]
Hi,

I have started AIVA as root user. After few days when I am trying to start aiva as normal user in my linux machine, it is not able to load all components. Please find below trace,

> aiva@4.2.0 start /data/installations/aiva/aiva-ISE/aiva
> bin/start

[ ------- Starting on local machine, not Docker ------- ]

> aiva@4.2.0 development /data/installations/aiva/aiva-ISE/aiva
> mkdir -p ./logs; NODE_ENV=development ./node_modules/forever/bin/forever --minUptime=1000 --spinSleepTime=1000 --killSignal=SIGTERM --uid aiva-ice-development -m 10 -a index.js | tee ./logs/aiva-ice-development.log

[Thu Aug 23 2018 08:19:39 GMT+0000 (utc)] INFO Authenticated database successfully
[Thu Aug 23 2018 08:19:40 GMT+0000 (utc)] INFO Starting aiva process
[Thu Aug 23 2018 08:19:40 GMT+0000 (utc)] INFO Starting poly-socketio server on port: 6466, expecting 4 IO clients
[Thu Aug 23 2018 08:19:40 GMT+0000 (utc)] INFO Starting socketIO client for js at 6466
[Thu Aug 23 2018 08:19:40 GMT+0000 (utc)] INFO Starting socketIO client for python at 6466
[Thu Aug 23 2018 08:19:40 GMT+0000 (utc)] INFO Deploying bot aiva-ice with adapter HTTPADAPTER
[Thu Aug 23 2018 08:19:40 GMT+0000 (utc)] INFO Starting socketIO client for python at 6466
[Thu Aug 23 2018 08:19:40 GMT+0000 (utc)] ERROR Traceback (most recent call last):
  File "/data/installations/aiva/aiva-ISE/aiva/lib/client.py", line 10, in <module>
    import six
ImportError: No module named six

[Thu Aug 23 2018 08:19:40 GMT+0000 (utc)] ERROR Traceback (most recent call last):
  File "/data/installations/aiva/aiva-ISE/aiva/node_modules/spacy-nlp/src/client.py", line 10, in <module>
    import six
ImportError: No module named six

**Comment by DivyaSundaram** [comment]
Hi,
I face an issue of- Expected number of IO clients failed to join in time.Once the application servers are restarted the chatbot is up for sometime and eventually fails again to work. Any help?
====Below are the logs:
[Mon Apr 15 2019 07:31:44 GMT+0000 (utc)] Authenticated database successfully
    [Mon Apr 15 2019 07:31:44 GMT+0000 (utc)] INFO Starting aiva process
    [Mon Apr 15 2019 07:31:44 GMT+0000 (utc)] INFO Starting poly-socketio server on port: 6467, expecting 4 IO clients
    [Mon Apr 15 2019 07:31:44 GMT+0000 (utc)] ERROR
    [Mon Apr 15 2019 07:31:44 GMT+0000 (utc)] ERROR
    [Mon Apr 15 2019 07:31:44 GMT+0000 (utc)] ERROR
    [Mon Apr 15 2019 07:31:44 GMT+0000 (utc)] INFO Deploying bot aivadev with adapter HTTPADAPTER
    Starting up aivadev
    [Mon Apr 15 2019 07:31:46 GMT+0000 (utc)] WARNING Expected /data/installations/aiva/aiva-IAE/aiva/scripts/server.config to assign a function to module.exports, got object
    [Mon Apr 15 2019 07:31:46 GMT+0000 (utc)] INFO global-client-js 1oK8mIFqpNepxpcQAABo joined, -101 remains
    [Mon Apr 15 2019 07:31:46 GMT+0000 (utc)] INFO All`enter code here` 4 IO clients have joined
    [Mon Apr 15 2019 07:33:24 GMT+0000 (utc)] ERROR {}
    [Mon Apr 15 2019 07:33:24 GMT+0000 (utc)] ERROR Expected number of IO clients failed to join in time
    [Mon Apr 15 2019 07:33:24 GMT+0000 (utc)] INFO Shutting down
    [Mon Apr 15 2019 07:33:24 GMT+0000 (utc)] INFO 1oK8mIFqpNepxpcQAABo left
    error: Forever detected script exited with code: 1
    error: Script restart attempt #1
